---
# SPDX-License-Identifier: GPL-3.0-or-later

- name: "Initialize distribution-specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "dist-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "dist-{{ ansible_distribution }}.yml"
    - "dist-{{ ansible_os_family }}.yml"
    - "dist-Default.yml"

- name: "Install packages"
  package:
    name: "{{ nginx_packages }}"
    state: "present"
  when: "nginx_packages is defined and nginx_packages is not none"

- name: "Setup system group"
  group:
    gid: "{{ nginx_group_id if nginx_group_id is not none else omit }}"
    name: "{{ nginx_group_name }}"
    system: "{{ 'no' if nginx_group_id is not none else 'yes' }}"
  when: "nginx_group_managed | bool"

- name: "Setup system user"
  user:
    create_home: "no"
    group: "{{ nginx_group_name }}"
    groups: "{{ nginx_user_groups }}"
    home: "{{ nginx_data_dir if nginx_data_dir is not none else omit }}"
    name: "{{ nginx_user_name }}"
    shell: "/sbin/nologin"
    system: "{{ 'no' if nginx_user_id is not none else 'yes' }}"
    uid: "{{ nginx_user_id if nginx_user_id is not none else omit }}"
  when: "nginx_user_managed | bool"

- name: "Setup directory for config files"
  file:
    state: "directory"
    dest: "{{ nginx_config_dir }}"
    owner: "root"
    group: "{{ nginx_group_name }}"
    mode: "0750"
  when: "nginx_config_dir != '/etc'"

- name: "Setup directory for certificate and key files"
  file:
    state: "directory"
    dest: "{{ nginx_pki_dir }}"
    owner: "root"
    group: "{{ nginx_group_name }}"
    mode: "0750"

- name: "Setup directory for pid and socket files"
  file:
    state: "directory"
    dest: "{{ nginx_run_dir }}"
    owner: "{{ nginx_user_name }}"
    group: "{{ nginx_group_name }}"
    mode: "0750"
  when: "nginx_run_dir != '/run'"

- name: "Setup directory for log files"
  file:
    state: "directory"
    dest: "{{ nginx_log_dir }}"
    owner: "{{ nginx_user_name }}"
    group: "root"
    mode: "0755"
  when: "nginx_log_dir != '/var/log'"

- name: "Setup directory for data files"
  file:
    state: "directory"
    dest: "{{ nginx_data_dir }}"
    owner: "{{ nginx_user_name }}"
    group: "{{ nginx_group_name }}"
    mode: "0750"

- name: "Setup config files"
  template:
    src: "{{ item['src'] }}"
    dest: "{{ nginx_config_dir }}/{{ item['name'] if item['name'] is defined else (item['src'] | basename | regex_replace('.j2', '')) }}"
    owner: "root"
    group: "{{ nginx_group_name }}"
    mode: "0640"
  with_items: "{{ nginx_config_files }}"
  when: "nginx_config_files is defined and nginx_config_files is not none"
  notify: "restart_nginx_services"

- name: "Copy certificate and key files"
  copy:
    src: "{{ item['src'] }}"
    dest: "{{ nginx_pki_dir }}/{{ item['name'] if item['name'] is defined else (item['src'] | basename) }}"
    owner: "root"
    group: "{{ nginx_group_name }}"
    mode: "0640"
  with_items: "{{ nginx_pki_files }}"
  notify: "restart_nginx_services"

- name: "Generate diffie-hellman parameters file"
  openssl_dhparam:
    path: "{{ nginx_pki_dir }}/dh.pem"
    size: "{{ nginx_pki_dh_length }}"
    owner: "root"
    group: "{{ nginx_group_name }}"
    mode: "0640"
  when: "nginx_pki_dh_gen | bool"

- name: "Generate default self signed key"
  openssl_privatekey:
    path: "{{ nginx_pki_dir }}/default.key"
    type: "RSA"
    size: "4096"
    owner: "root"
    group: "{{ nginx_group_name }}"
    mode: "0640"
  when: "nginx_pki_selfsigned_gen | bool"

- name: "Generate default self signed csr"
  openssl_csr:
    path: "{{ nginx_pki_dir }}/default.csr"
    privatekey_path: "{{ nginx_pki_dir }}/default.key"
    common_name: "{{ ansible_hostname }}"
    owner: "root"
    group: "root"
    mode: "0600"
  when: "nginx_pki_selfsigned_gen | bool"

- name: "Generate default self signed certificate"
  openssl_certificate:
    path: "{{ nginx_pki_dir }}/default.crt"
    privatekey_path: "{{ nginx_pki_dir }}/default.key"
    csr_path: "{{ nginx_pki_dir }}/default.csr"
    provider: "selfsigned"
    selfsigned_digest: "sha512"
    signature_algorithms:
      - "sha512WithRSAEncryption"
    owner: "root"
    group: "{{ nginx_group_name }}"
    mode: "0640"
  when: "nginx_pki_selfsigned_gen | bool"

- name: "Check stat of logrotate dynamic config directory"
  stat:
    path: "{{ nginx_logrotate_config_d_dir }}"
  register: "nginx_logrotate_config_d_dir_stat_result"
  when:
    - "nginx_logrotate_manage | bool"
    - "nginx_logrotate_config_d_dir is defined and nginx_logrotate_config_d_dir is not none"

- name: "Setup logrotate config files"
  template:
    src: "{{ item['src'] }}"
    dest: "{{ nginx_logrotate_config_d_dir }}/{{ item['name'] if item['name'] is defined else (item['src'] | basename | regex_replace('.j2', '') | regex_replace('.logrotate', '')) }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ nginx_logrotate_d_config_files }}"
  when:
    - "nginx_logrotate_manage | bool"
    - "nginx_logrotate_config_d_dir_stat_result['stat']['exists'] | bool"
    - "nginx_logrotate_d_config_files is defined and nginx_logrotate_d_config_files is not none"

- name: "Setup tmpfiles.d config files"
  template:
    src: "{{ item['src'] }}"
    dest: "{{ tmpfiles_d_config_dir if tmpfiles_d_config_dir is defined else '/etc/tmpfiles.d' }}/{{ item['name'] if item['name'] is defined else (item['src'] | basename | regex_replace('.j2', '') | regex_replace('.tmpfile', '.conf')) }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ nginx_tmpfiles_d_files }}"
  when: "nginx_tmpfiles_d_files is defined and nginx_tmpfiles_d_files is not none"

- name: "Setup systemd service files"
  template:
    src: "{{ item['src'] }}"
    dest: "{{ systemd_config_dir if systemd_config_dir is defined else '/etc/systemd' }}/system/{{ item['name'] if item['name'] is defined else (item['src'] | basename | regex_replace('.j2', '')) }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ nginx_systemd_service_files }}"
  when:
    - "nginx_systemd_managed | bool"
    - "nginx_systemd_service_files is defined and nginx_systemd_service_files is not none"
    - "ansible_service_mgr == 'systemd'"
  notify: "restart_nginx_services"

- name: "Setup systemd timer files"
  template:
    src: "{{ item['src'] }}"
    dest: "{{ systemd_config_dir if systemd_config_dir is defined else '/etc/systemd' }}/system/{{ item['name'] if item['name'] is defined else (item['src'] | basename | regex_replace('.j2', '')) }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ nginx_systemd_timer_files }}"
  when:
    - "nginx_systemd_managed | bool"
    - "nginx_systemd_timer_files is defined and nginx_systemd_timer_files is not none"
    - "ansible_service_mgr == 'systemd'"

- name: "Check status of systemd services"
  systemd:
    daemon_reload: "yes"
    enabled: "{{ 'yes' if item['enabled'] is defined and item['enabled'] else omit }}"
    name: "{{ item['name'] if item['name'] is defined else (item['src'] | basename | regex_replace('.j2', '')) }}"
    state: "{{ 'started' if item['started'] is defined and item['started'] else omit }}"
  with_items: "{{ nginx_systemd_service_files }}"
  when:
    - "nginx_systemd_managed | bool"
    - "nginx_systemd_service_files is defined and nginx_systemd_service_files is not none"
    - "ansible_service_mgr == 'systemd'"

- name: "Check status of systemd timers"
  systemd:
    daemon_reload: "yes"
    enabled: "{{ 'yes' if item['enabled'] is defined and item['enabled'] else omit }}"
    name: "{{ item['name'] if item['name'] is defined else (item['src'] | basename | regex_replace('.j2', '')) }}"
    state: "{{ 'started' if item['started'] is defined and item['started'] else omit }}"
  with_items: "{{ nginx_systemd_timer_files }}"
  when:
    - "nginx_systemd_managed | bool"
    - "nginx_systemd_timer_files is defined and nginx_systemd_timer_files is not none"
    - "ansible_service_mgr == 'systemd'"
